export const state = () => ({
  stacks: [
    {
      id: 38,
      name: "Javascript",
      img: "js.png",
      alias: "javascript",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 38,
      name: "Typescript",
      img: "ts.png",
      alias: "javascript",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 38,
      name: "Python",
      img: "python.png",
      alias: "javascript",
      type: "dev",
      bg: "#008100",
    },
  ],
  tools: [
    {
      id: 1,
      name: "Vue.js",
      img: "vue.js.png",
      alias: "vue",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 1,
      name: "Nuxt.js",
      img: "nuxt.png",
      alias: "vue",
      type: "dev",
      bg: "#008100",
    },

    {
      id: 31,
      name: "React",
      img: "react.png",
      alias: "react",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 36,
      name: "Node Js",
      img: "nodejs.png",
      alias: "nodejs",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 12,
      name: "Figma",
      img: "figma.png",
      alias: "figma",
      type: "product",
      bg: "#008100",
    },
    {
      id: 12,
      name: "Django",
      img: "django.png",
      alias: "django",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 40,
      name: "MongoDB",
      img: "mongodb.png",
      alias: "mongodb",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 31,
      name: "Node Sass",
      img: "scss.png",
      alias: "react",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 42,
      name: "Tailwind",
      img: "tailwind.png",
      alias: "postgresql",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 42,
      name: "Webpack",
      img: "webpack.png",
      alias: "webpack",
      type: "dev",
      bg: "#008100",
    },
  ],
  platforms: [
    {
      id: 27,
      name: "GitHub",
      img: "github.png",
      alias: "github",
      type: "devO",
      bg: "#008100",
    },
    {
      id: 27,
      name: "Netlify",
      img: "netlify.png",
      alias: "netlify",
      type: "dev",
      bg: "#008100",
    },
    {
      id: 25,
      name: "Heroku",
      img: "heroku.png",
      alias: "aws",
      type: "dev",
      bg: "#008100",
    },

    {
      id: 3,
      name: "Postman",
      img: "postman.png",
      alias: "postman",
      type: "QA",
      bg: "#008100",
    },
    {
      id: 8,
      name: "Notion",
      img: "notion.png",
      alias: "notion",
      type: "QA",
      bg: "#008100",
    },
  ],
  projects: [
    {
      id: 1,
      name: "GitHub",
      img: "github.png",
      desc: "",
      liveUrl: "github",
      codeUrl: "devO",
    },
  ],
  experiences: [
    {
      id: 1,
      name: "MLH Fellowship",
      position: "Software Engineering Prep Fellow",
      img: "github.png",
      desc: "",
    },
  ],
});
